project_id = "jdhtavxktaxrrvvhxroe"

[functions.generate-resume-bullets]
verify_jwt = false

[functions.generate-resume-summary]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.generate-cold-email]
verify_jwt = false
