import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Terms = () => (
  <>
    <Navbar />
    <main className="py-16">
      <div className="container max-w-3xl mx-auto">
        <h1 className="font-display text-3xl md:text-4xl font-bold">Terms of Service</h1>
        <div className="mt-6 space-y-4 text-body leading-relaxed text-sm">
          <p>Last updated: March 2026</p>
          <h2 className="text-lg font-semibold text-foreground pt-4">Use of Service</h2>
          <p>CareerToolkit AI provides free AI-powered career tools. By using our tools, you agree to use them for lawful purposes only.</p>
          <h2 className="text-lg font-semibold text-foreground pt-4">Generated Content</h2>
          <p>Content generated by our tools is provided as-is. You are responsible for reviewing and editing generated content before using it professionally.</p>
          <h2 className="text-lg font-semibold text-foreground pt-4">Limitations</h2>
          <p>We reserve the right to limit usage, modify features, or discontinue the service at any time without notice.</p>
        </div>
      </div>
    </main>
    <Footer />
  </>
);

export default Terms;
